# $OpenBSD$

TBB_DISTNAME =		torbutton
TBB_DISTVERS =		1.9.0.0
COMMENT =		torbutton Firefox Add on: Part of Tor Browser Bundle

TBB_MAKE_COMMAND =	./makexpi.sh
TBB_BUILD_SUBDIR =	pkg

MODULES =		www/tbb

GUID =			torbutton@torproject.org

.include <bsd.port.mk>
