# $OpenBSD$

TBB_DISTNAME =		tor-launcher
TBB_DISTVERS =		0.2.7.2
COMMENT =		tor-launcher add-on: Part of the Tor Browser Bundle

USE_GMAKE =		Yes
ALL_TARGET =		package
MODULES =		www/tbb

GUID =			tor-launcher@torproject.org

.include <bsd.port.mk>
