# $OpenBSD$

V =		0.9.3
COMMENT =	bitcoin wallet/client
DISTNAME =	bitcoin-${V}
CATEGORIES =	net

GH_ACCOUNT =	bitcoin
GH_PROJECT =	bitcoin
GH_TAGNAME =	v${V}
GH_COMMIT =	40d20412ff173e8eea2f456fd749663c8cabda18

HOMEPAGE =	https://bitcoin.org
MAINTAINER =	attila <attila@stalphonsos.com>

# ?
PERMIT_PACKAGE_CDROM =	No

WANTLIB += c

LIB_DEPENDS =

CONFIGURE_STYLE =	automake

NO_TEST =	Yes

do-install:
	echo write me

.include <bsd.port.mk>
